//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate_type
    {
        public certificate_type()
        {
            this.certificates = new HashSet<certificate>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string nominal { get; set; }
        public double cost { get; set; }
        public System.DateTime created { get; set; }
        public bool deleted { get; set; }
        public bool c_type { get; set; }
    
        public virtual ICollection<certificate> certificates { get; set; }
    }
}
