//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate_type
    {
        public certificate_type()
        {
            this.certificates = new HashSet<certificate>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string nominal { get; set; }
        public double cost { get; set; }
        public System.DateTime created { get; set; }
        public bool deleted { get; set; }
        public bool c_type { get; set; }
    
        public virtual ICollection<certificate> certificates { get; set; }
    }
}
