//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate
    {
        public int id { get; set; }
        public string bar_number { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public System.DateTime modified { get; set; }
        public System.DateTime date_end { get; set; }
        public bool active { get; set; }
        public int c_id { get; set; }
    
        public virtual users user { get; set; }
        public virtual certificate_type certificate_type { get; set; }
    }
}
