//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCard
    {
        public DiscountCard()
        {
            this.race_data = new HashSet<race_data>();
        }
    
        public int Id { get; set; }
        public Nullable<int> idOwner { get; set; }
        public Nullable<int> idSeller { get; set; }
        public string Number { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public string SalePlace { get; set; }
        public int IdDiscountCardGroup { get; set; }
        public bool IsBlocked { get; set; }
    
        public virtual users owner { get; set; }
        public virtual program_users seller { get; set; }
        public virtual DiscountCardGroup DiscountCardGroup { get; set; }
        public virtual ICollection<race_data> race_data { get; set; }
    }
}
