//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCard
    {
        public DiscountCard()
        {
            this.race_data = new HashSet<race_data>();
        }
    
        public int Id { get; set; }
        public Nullable<int> idOwner { get; set; }
        public Nullable<int> idSeller { get; set; }
        public string Number { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime ValidUntil { get; set; }
        public string SalePlace { get; set; }
        public int IdDiscountCardGroup { get; set; }
        public bool IsBlocked { get; set; }
    
        public virtual users owner { get; set; }
        public virtual program_users seller { get; set; }
        public virtual DiscountCardGroup DiscountCardGroup { get; set; }
        public virtual ICollection<race_data> race_data { get; set; }
    }
}
