//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscountCardGroup
    {
        public DiscountCardGroup()
        {
            this.DiscountCards = new HashSet<DiscountCard>();
        }
    
        public int Id { get; set; }
        public short PercentOfDiscount { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<DiscountCard> DiscountCards { get; set; }
    }
}
