//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuel
    {
        public int id { get; set; }
        public Nullable<int> car_id { get; set; }
        public double fuel_value { get; set; }
        public System.DateTime created { get; set; }
        public int sign { get; set; }
        public string comment { get; set; }
    
        public virtual karts kart { get; set; }
    }
}
