//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fuel
    {
        public int id { get; set; }
        public Nullable<int> car_id { get; set; }
        public double fuel_value { get; set; }
        public System.DateTime created { get; set; }
        public int sign { get; set; }
        public string comment { get; set; }
    
        public virtual karts kart { get; set; }
    }
}
