//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class groups
    {
        public groups()
        {
            this.users = new HashSet<users>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string sale { get; set; }
        public Nullable<System.DateTime> created { get; set; }
        public System.DateTime modified { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
