//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class jurnal
    {
        public jurnal()
        {
            this.user_cash = new HashSet<user_cash>();
            this.cassas = new HashSet<cassa>();
        }
    
        public int id { get; set; }
        public int tp { get; set; }
        public string comment { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<int> race_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual races race { get; set; }
        public virtual users user { get; set; }
        public virtual ICollection<user_cash> user_cash { get; set; }
        public virtual ICollection<cassa> cassas { get; set; }
    }
}
