//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class jurnal
    {
        public jurnal()
        {
            this.user_cash = new HashSet<user_cash>();
            this.cassas = new HashSet<cassa>();
        }
    
        public int id { get; set; }
        public int tp { get; set; }
        public string comment { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<int> race_id { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual races race { get; set; }
        public virtual users user { get; set; }
        public virtual ICollection<user_cash> user_cash { get; set; }
        public virtual ICollection<cassa> cassas { get; set; }
    }
}
