//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class karts
    {
        public karts()
        {
            this.fuels = new HashSet<fuel>();
            this.race_data = new HashSet<race_data>();
            this.messages = new HashSet<messages>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public string transponder { get; set; }
        public string color { get; set; }
        public System.DateTime created { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public bool repair { get; set; }
        public Nullable<int> message_id { get; set; }
        public bool wait { get; set; }
    
        public virtual ICollection<fuel> fuels { get; set; }
        public virtual ICollection<race_data> race_data { get; set; }
        public virtual ICollection<messages> messages { get; set; }
    }
}
