//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class logins
    {
        public int id { get; set; }
        public Nullable<int> stat { get; set; }
        public System.DateTime created { get; set; }
        public int user_id { get; set; }
    
        public virtual program_users program_users { get; set; }
    }
}
