//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public int m_type { get; set; }
        public string message { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string subject { get; set; }
        public Nullable<int> id_pilot { get; set; }
        public Nullable<int> id_kart { get; set; }
        public Nullable<int> id_program_user { get; set; }
    
        public virtual users user { get; set; }
        public virtual karts kart { get; set; }
        public virtual program_users program_users { get; set; }
    }
}
