//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class messages
    {
        public int id { get; set; }
        public int m_type { get; set; }
        public string message { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string subject { get; set; }
        public Nullable<int> id_pilot { get; set; }
        public Nullable<int> id_kart { get; set; }
        public Nullable<int> id_program_user { get; set; }
    
        public virtual users user { get; set; }
        public virtual karts kart { get; set; }
        public virtual program_users program_users { get; set; }
    }
}
