//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentix.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class crazykartContainer : DbContext
    {
        public crazykartContainer()
            : base("name=crazykartContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cassa> cassa { get; set; }
        public DbSet<certificate> certificates { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<certificate_type> certificate_type { get; set; }
        public DbSet<fuel> fuel { get; set; }
        public DbSet<karts> karts { get; set; }
        public DbSet<groups> groups { get; set; }
        public DbSet<jurnal> jurnal { get; set; }
        public DbSet<races> races { get; set; }
        public DbSet<tracks> tracks { get; set; }
        public DbSet<logins> logins { get; set; }
        public DbSet<messages> messages { get; set; }
        public DbSet<noracekart> noracekart { get; set; }
        public DbSet<prices> prices { get; set; }
        public DbSet<race_modes> race_modes { get; set; }
        public DbSet<program_users> program_users { get; set; }
        public DbSet<race_data> race_data { get; set; }
        public DbSet<race_times> race_times { get; set; }
        public DbSet<settings> settings { get; set; }
        public DbSet<user_cash> user_cash { get; set; }
        public DbSet<DiscountCard> DiscountCards { get; set; }
        public DbSet<DiscountCardGroup> DiscountCardGroups { get; set; }
        public DbSet<Petroleum> Petroleums { get; set; }
    }
}
