//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class noracekart
    {
        public int id { get; set; }
        public string transponder { get; set; }
        public Nullable<int> race_id { get; set; }
        public System.DateTime created { get; set; }
    
        public virtual races race { get; set; }
    }
}
