//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Petroleum
    {
        public int Id { get; set; }
        public double litres { get; set; }
        public int program_users_id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual program_users program_users { get; set; }
    }
}
