//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class program_users
    {
        public program_users()
        {
            this.logins = new HashSet<logins>();
            this.messages = new HashSet<messages>();
            this.DiscountCards = new HashSet<DiscountCard>();
            this.Petrols = new HashSet<Petroleum>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public Nullable<int> stat { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public bool deleted { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string barcode { get; set; }
    
        public virtual ICollection<logins> logins { get; set; }
        public virtual ICollection<messages> messages { get; set; }
        public virtual ICollection<DiscountCard> DiscountCards { get; set; }
        public virtual ICollection<Petroleum> Petrols { get; set; }
    }
}
