//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class race_times
    {
        public int id { get; set; }
        public Nullable<int> lap { get; set; }
        public decimal seconds { get; set; }
        public System.DateTime created { get; set; }
        public int member_id { get; set; }
    
        public virtual race_data race_data { get; set; }
    }
}
