//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class races
    {
        public races()
        {
            this.jurnals = new HashSet<jurnal>();
            this.noracekarts = new HashSet<noracekart>();
            this.race_data = new HashSet<race_data>();
            this.is_race = false;
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> racedate { get; set; }
        public string raceid { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime modified { get; set; }
        public Nullable<int> stat { get; set; }
        public int track_id { get; set; }
        public bool light_mode { get; set; }
        public Nullable<bool> is_race { get; set; }
    
        public virtual tracks track { get; set; }
        public virtual ICollection<jurnal> jurnals { get; set; }
        public virtual ICollection<noracekart> noracekarts { get; set; }
        public virtual ICollection<race_data> race_data { get; set; }
    }
}
