//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class race_modes
    {
        public race_modes()
        {
            this.is_deleted = false;
            this.prices = new HashSet<prices>();
            this.race_data = new HashSet<race_data>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int length { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual ICollection<prices> prices { get; set; }
        public virtual ICollection<race_data> race_data { get; set; }
    }
}
