//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class race_modes
    {
        public race_modes()
        {
            this.is_deleted = false;
            this.prices = new HashSet<prices>();
            this.race_data = new HashSet<race_data>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int length { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual ICollection<prices> prices { get; set; }
        public virtual ICollection<race_data> race_data { get; set; }
    }
}
