//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class race_times
    {
        public int id { get; set; }
        public Nullable<int> lap { get; set; }
        public decimal seconds { get; set; }
        public System.DateTime created { get; set; }
        public int member_id { get; set; }
    
        public virtual race_data race_data { get; set; }
    }
}
