//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rentix.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracks
    {
        public tracks()
        {
            this.is_deleted = false;
            this.races = new HashSet<races>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> length { get; set; }
        public string file { get; set; }
        public System.DateTime created { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual ICollection<races> races { get; set; }
    }
}
