//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tracks
    {
        public tracks()
        {
            this.is_deleted = false;
            this.races = new HashSet<races>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> length { get; set; }
        public string file { get; set; }
        public System.DateTime created { get; set; }
        public bool is_deleted { get; set; }
    
        public virtual ICollection<races> races { get; set; }
    }
}
