//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokard_Timing.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_cash
    {
        public int id { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<double> sum { get; set; }
        public bool sign { get; set; }
        public System.DateTime created { get; set; }
        public int doc_id { get; set; }
    
        public virtual users user { get; set; }
        public virtual jurnal jurnal { get; set; }
    }
}
